### ISSUE TITLE
SurvivalFly & Passable false positive when walking down slabs.

### ISSUE THREAD

**Issue by mibby** [NoCheatPlus/Issues#114]
A member is getting loads of survivalfly and passable false positives going down slabs. Also seems to occur when walking on fences, chests, etc.

NoCheatPlus - compiled source as of this commit. https://github.com/NoCheatPlus/NoCheatPlus/commit/0be4373310d1dc70c86428d650223cc3171babb9
CompatNoCheatPlus dev 84. http://ci.md-5.net/job/CompatNoCheatPlus/changes
ProtocolLib dev 258. http://ci.dmulloy2.net/job/ProtocolLib/changes
PaperSpigot dev 486.

![link1](http://i.imgur.com/qCPBukk.png)
![link2](http://i.imgur.com/S820Oqt.png)

```
    passable:
      active: true
      raytracing:
        active: true
        blockchangeonly: false
      actions: cancel vl>10 log:passable:0:5:if cancel vl>50 log:passable:0:5:icf cancel
      untracked:
        teleport:
          active: true
        command:
          active: true
          tryteleport: true
          prefixes:
          - sethome
          - home set
          - setwarp
          - warp set
          - setback
          - set back
          - back set
    survivalfly:
      active: true
      extended:
        vertical-accounting: true
      stepheight: default
      setbackpolicy:
        falldamage: true
        voidtovoid: true
      actions: log:flyshort:3:10:f cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1500 log:flylong:0:5:cif cancel cmd:kickfly
      hover:
        active: true
        step: 5
        ticks: 85
        loginticks: 0
        falldamage: true
        sfviolation: 500
```
