### ISSUE TITLE
Structure void blocks give passable violations

### ISSUE THREAD

**Issue by Ullarah** [NoCheatPlus/Issues#277]
Hi,

I use structure void blocks in some of my plugins, and it seems that players are getting repelled by them with a passable violation. Is there a way to exclude a block from a passable check?

I don't want to add a passable exception to players.

Thanks!

```
16-09-18 15:10:23 [INFO] Ullarah failed Passable: moved into a block (217) from 163.97, 66.00, 261.82 to 164.07, 66.00, 261.79 distance 0.10 . VL 11.
```

```
#### Server ####
git-Spigot-078e2f8-7f9fbe5 ~MC: 1.10.2~
  detected: 1.10.2
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022
MCAccess: 1.10 / Spigot-CB-1.10_R1
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
  defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
```
