### ISSUE TITLE
Dying with shield wielded triggers SurvivalFly detection on subsequent walking

### ISSUE THREAD

**Issue by Kakifrucht** [NoCheatPlus/Issues#393]
#### Short description of the issue.
When dying while wielding ones right handed shield, after respawning the player will be lagged behind due to SurvivalFly detection. Wielding the shield once again (right clicking) will fix the issue.
#### Complete output of the _ncp version_ command (please prefer text here).
````
 ---- Version information ----
#### Server ####
git-Spigot-d4f98a3-cb61ac0 MC: 1.11.2
  detected: 1.11.2
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1066
MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
  defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
````
#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happens, but only if shield is in off hand.
#### Have you made any (noteworthy) changes to the default configuration of NCP?
No, I was using the default configuration.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

Log entry for violation:
17-03-04 03:33:55 [INFORMATION] Kakifrucht failed SurvivalFly: tried to move unexpectedly. VL 17.

Manually resetting the off hand item via BukkitAPI also fixes the issue as a temporary workaround.
