### ISSUE TITLE
CraftBook Sign Copier mechanic throws out autosign false positive violations.

### ISSUE THREAD

**Issue by mibby** [NoCheatPlus/Issues#451]
CraftBook dev 154
NoCheatPlus dev 111

Using the SignCopier mechanic in craftbook, players throw out NoCheatPlus block place auto sign violations. Is there any way to prevent this or add compatibility through cncp?

```
    autosign:
      active: true
      skipempty: false
      actions: cancel vl>10 log:autosign:0:12:i cancel
```
