### ISSUE TITLE
Fight angle false positives with enderman farm on slab blocks.

### ISSUE THREAD

**Issue by mibby** [NoCheatPlus/Issues#456]
NoCheatPlus dev 111 (2 commits newer - compiled source manually as of https://github.com/NoCheatPlus/NoCheatPlus/commit/8b02a7ce4cec07a11e200b9463489ccbfa037fa9)
ProtocolLib dev 366
CNCP 88
Paper dev 1104 (Spigot 1.11.2)

```
    angle:
      active: true
      threshold: 50
      actions: cancel vl>140 cmdc:aimbotnotifyb1:1:11 cancel vl>260 cmdc:aimbotnotifyb2:1:11 cancel vl>380 cmdc:aimbotnotifyb2:1:11 cancel
```

Players who kill enderman mobs with a sword at farms that are designed with the mob falling a half slab downwards throw out fight angle false positives when killing the mobs. Players turn back and forth often between the two 'slots' to kill the mobs that fall down. I'm assuming them rotating their screen and then hitting the mobs a half slab down is what is causing the false positive readings.

Rotate > kill > rotate > kill > rotate > kill, repeat forever until no more mobs.
![link](http://i.imgur.com/kjeTDco.png)
![link2](http://i.imgur.com/qW9KAKz.png)

![link3](http://i.imgur.com/kBgoPgx.png)
![link4](http://i.imgur.com/QNw5Sta.png)
![link5](http://i.imgur.com/VwNQUQ3.png)
![link6](http://i.imgur.com/YL4sWQf.png)
![link7](http://i.imgur.com/8s0JBSs.png)
