### ISSUE TITLE
FastHeal enabled, despite shouldn't.

### ISSUE THREAD

**Issue by mibby** [NoCheatPlus/Issues#533]
NoCheatPlus as of commit https://github.com/NoCheatPlus/NoCheatPlus/commit/cbfcecf2b49de24694a0335ff4e4eb821ca64cf2

```
    fastheal:
      active: true
      interval: 4000
      buffer: 1000
      actions: cancel vl>10 cmdc:fastheal1:1:15 cancel vl>45 cmdc:fastheal2:1:12 cancel
```

Whenever someone eats in one of my arenas (duel in my case), they throw out FastHeal violations. The arena has hunger enabled and food eating is _not_ instant use/restore. Eating outside the arena, no violations occur.

Is the check currently broken?
