### ISSUE TITLE
NCP False flagging flight on path block

### ISSUE THREAD

**Issue by p9sq** [NoCheatPlus/Issues#670]
#### Short description of the issue.
Falsely flagging flight while standing on path block

#### Complete output of the _ncp version_ command (please prefer text here).
```
---- Version information ----
#### NoCheatPlus ####
Plugin: 3.16.0-RC-sMD5NET-b1134
MCAccess: 1.4.6-1.11.2I? / Bukkit-API
Features:
   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
   defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
```

#### How to reproduce the issue (is it random / always happens / side conditions)?
The issue is always happening and idk how to fix it

#### Have you made any (noteworthy) changes to the default configuration of NCP?
My server is a multi-version anarchy server and I've disabled all checks, but not survivalfly.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
NCP Is the only anti-cheat plugin I have installed

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Do I have to?
